---
#
# User configuration
#
user:
  name: name
  full_name: "full name"
  primary_group: users
  additional_groups: docker,wheel,render
  # /bin/bash or /bin/zsh
  shell: /bin/bash
  # See country list by running `reflector --list-countries`
  country: "United States"

git:
  name: "{{ user['full_name'] }}"
  # obfuscated a little so bots won't find it
  email_b64: "bG9nYW5AbG9nYW5tYXJjaGlvbmUuY29t"
  # can be "cache", "store", "osxkeychain", or "manager"
  helper: "cache"
  # can be "true" or "false"
  rebase: "true"
  # see this https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---color-movedltmodegt
  colorMoved: "zebra"

#
# Miscellaneous
#

# desktop environment to install
# "kde" or "gnome"
desktop: kde

# only AMD or Intel CPUs are currently supported
# true or false
install_microcode: true

# whether to enable printing/scanning or not
# true or false
enable_printing: true

# whether to detect the scanner or not
# true or false
detect_scanner: true

# whether to enable bluetooth or not
# true or false
enable_bluetooth: true

# whether to install laptop tools
# true or false
laptop: false

# how many parallel downloads to run at once
pacman:
  parallel_downloads: 10

# set aur helper
# supported helpers are here https://github.com/kewlfft/ansible-aur#kewlfftauraur-module
aur_helper: yay

#
# Services
#

# if not using LVM, disable it
# true or false
disable_lvm: false

# if not using systemd homed, disable it
# true or false
disable_systemd_homed: true

#
# Packages
#
packages:
  - alsa-firmware
  - alsa-plugins
  - alsa-utils
  - bash
  - bash-completion
  - cadaver
  - chromium
  - code
  - curl
  - docker
  - docker-compose
  - dosfstools
  - e2fsprogs
  - exfatprogs
  - ffmpeg
  - firefox
  - flatpak
  - fwupd
  - fzf
  - git
  - gnupg
  - gparted
  - gst-libav
  - gst-plugins-bad
  - gst-plugins-base
  - gst-plugins-good
  - gvfs
  - gvfs-afc
  - gvfs-gphoto2
  - gvfs-smb
  - htop
  - ifuse
  - inkscape
  - inetutils
  - iotop
  - iperf3
  - iputils
  - jq
  - keepassxc
  - kubectl
  - lame
  - libimobiledevice
  - linux-firmware
  - man
  - man-db
  - man-pages
  - minicom
  - ncdu
  - neofetch
  - networkmanager
  - nextcloud-client
  - nextcloud-client-cloudproviders
  - ntfs-3g
  - openresolv
  - openssh
  - openvpn
  - picocom
  - pipewire
  - pipewire-alsa
  - pkgstats
  - qbittorrent
  - rsync
  - screen
  - solaar
  - sudo
  - texmaker
  - texlive-latexextra
  - thunar
  - tree
  - unrar-free
  - unzip
  - usbutils
  - vi
  - vim
  - vlc
  - wget
  - wireguard-tools
  - wireplumber
  - wpa_supplicant
  # Needed for GTK apps that run as Flatpaks
  - xdg-desktop-portal-gtk
  - xfsprogs
  - youtube-dl
  - zip
  - zsh
  - zsh-completions
  - zstd
  - steam

aur_packages:
  - 7-zip-bin
  - etcher-bin
  - joplin-appimage
  - rpi-imager-bin
  - svgo
  - variety-git

flatpaks:
  - com.slack.Slack
  - com.spotify.Client
  - org.freedesktop.Platform.ffmpeg-full/x86_64/23.08
  - org.freedesktop.Platform.openh264/x86_64/2.3.0
  - org.gtk.Gtk3theme.Adwaita-dark
  - org.gtk.Gtk3theme.Yaru-dark
  - org.gtk.Gtk3theme.Yaru-light
  # See other themes here
  # flatpak remote-ls flathub | grep org.gtk.Gtk3theme

base_fonts:
  - adobe-source-code-pro-fonts
  - adobe-source-sans-pro-fonts
  - adobe-source-serif-pro-fonts
  - gnu-free-fonts
  - noto-fonts
  - noto-fonts-cjk
  - noto-fonts-emoji
  - powerline-fonts
  - ttf-anonymous-pro
  - ttf-dejavu
  - otf-cascadia-code
  - ttf-cascadia-code
  - ttf-hack

vscode_extension_list:
  - arcticicestudio.nord-visual-studio-code
  - dracula-theme.theme-dracula
  - eamodio.gitlens
  - ms-azuretools.vscode-docker
  - ms-python.python
  - redhat.ansible
  - streetsidesoftware.code-spell-checker
  - vscode-icons-team.vscode-icons

printing_scanning_packages:
  - cups
  - cups-pdf
  - sane
  - sane-airscan
  - simple-scan

printing_scanning_aur_packages:
  - brlaser-git
  - brscan4
