---
- name: Create user
  ansible.builtin.user:
    name: "{{ user.name }}"
    comment: "{{ user.full_name }}"
    groups: "{{ user.additional_groups }}"
    append: yes
    shell: "/usr/bin/zsh"
    state: present
  become: true

- name: Git config user.name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git.name }}"

- name: Git config user.email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git.email }}"

- name: Set zsh as default shell
  ansible.builtin.user:
    name: "{{ user.name }}"
    shell: /usr/bin/zsh
  become: true

- name: Install Oh My Zsh
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    creates: "/home/{{ user.name }}/.oh-my-zsh"
  become: true
  become_user: "{{ user.name }}"

- name: Create .zshrc
  become: true
  become_user: '{{ user.name }}'
  ansible.builtin.template:
    src: zshrc.j2
    dest: '~{{ user.name}}/.zshrc'
    backup: true
    mode: 'u=rw,go=r'

- name: Install VS Code extensions
  ansible.builtin.shell: code --install-extension {{ item }}
  with_items: "{{ vscode_extension_list }}"
  changed_when: no

- name: Mask systemd services - lvm
  ansible.builtin.systemd:
    name: "{{ item }}"
    masked: yes
  become: true
  with_items:
    - lvm2-lvmetad.service
    - lvm2-lvmetad.socket
    - lvm2-monitor.service
  when: disable_lvm

- name: Mask systemd services - systemd homed
  ansible.builtin.systemd:
    name: "{{ item }}"
    masked: yes
  become: true
  with_items:
    - systemd-homed.service
    - systemd-userdbd.service
    - systemd-userdbd.socket
  when: disable_systemd_homed
