---
- name: Install kde desktop environment
  when: desktop == "kde"
  block:
    - name: Install Plasma
      community.general.pacman:
        name:
          # KDE apps/bundles
          - plasma-meta
          - plasma-workspace
          - kde-sdk-meta
          - kde-system-meta
          - kde-utilities-meta
          - sddm
          - xdg-desktop-portal-kde
          # Individual apps
          - colord-kde
          - ffmpegthumbs
          - gwenview
          - kamoso
          - kcolorchooser
          - kdeconnect
          - kdegraphics-mobipocket
          - kdegraphics-thumbnailers
          - kdenetwork-filesharing
          - kfilemetadata
          - kio-extras
          - kio-fuse
          - kio-zeroconf
          - kleopatra
          - kmix
          - kolourpaint
          - kparts
          - okular
          - spectacle
          - svgpart
        state: present
      become: true

    - name: Start systemd service - sddm.service
      ansible.builtin.systemd:
        name: sddm.service
        enabled: yes
      become: true

- name: Install gnome desktop environment
  when: desktop == "gnome"
  block:
    - name: Install Gnome
      community.general.pacman:
        name:
          - gnome
          - gnome-shell
          - gnome-control-center
          - gdm
          - xdg-desktop-portal-gnome
        state: present
      become: true

    - name: Start systemd service - gdm.service
      ansible.builtin.systemd:
        name: gdm.service
        enabled: yes
      become: true
