---
- name: Install Xorg
  community.general.pacman:
    name:
      - xorg-xwayland
    state: present
  become: true

- name: Detect GPU
  ansible.builtin.shell: |
    set -o pipefail
    lspci | grep -E "VGA|3D controller" | sed -E 's/.*: (.*)/\1/'
  register: gpu_result
  changed_when: no

- name: Set GPU type fact
  ansible.builtin.set_fact:
    gpu_type: "{{ 'AMD' if 'AMD' in gpu_result.stdout or 'ATI' in gpu_result.stdout else ('Intel' if 'Intel' in gpu_result.stdout else ('NVIDIA' if 'NVIDIA' in gpu_result.stdout else 'Unknown')) }}"

- name: Display detected GPU
  ansible.builtin.debug:
    msg: "Detected GPU: {{ gpu_type }} ({{ gpu_result.stdout | trim }})"

- name: Install GPU drivers (AMD)
  community.general.pacman:
    name:
      - mesa
      - mesa-utils
      - xf86-video-amdgpu
      - mesa-vdpau
      - libva-mesa-driver
      - vulkan-radeon
      - rocm-hip-runtime
      - rocm-hip-sdk
      - hip-runtime-amd
      - rocm-core
      - rocm-opencl-runtime
      - rocm-opencl-sdk
    state: present
  become: true
  when: gpu_type == 'AMD'

- name: Install GPU drivers (Intel)
  community.general.pacman:
    name:
      - mesa
      - mesa-utils
      - xf86-video-intel
      - intel-media-driver
      - libva-intel-driver
      - vulkan-intel
      - intel-compute-runtime
      - opencl-clover-mesa
    state: present
  become: true
  when: gpu_type == 'Intel'

- name: Install GPU drivers (NVIDIA)
  community.general.pacman:
    name:
      - mesa
      - mesa-utils
      - nvidia-dkms
      - nvidia-utils
      - cuda
      - opencl-nvidia
    state: present
  become: true
  when: gpu_type == 'NVIDIA'